stage: sft
do_train: true
model_name_or_path: OpenDFM/ChemDFM-v1.0-13B
dataset: dataset_training1kpts_auto
dataset_dir: ./data/processed/chemdfm_prompts
template: chemdfm
finetuning_type: lora
lora_target: q_proj,k_proj,v_proj,o_proj,gate_proj,up_proj,down_proj
output_dir: finetuned_models/chemdfm-qlora-1kpts_auto
per_device_train_batch_size: 1
gradient_accumulation_steps: 16
num_train_epochs: 3.0
learning_rate: 0.0001
cutoff_len: 2048
packing: true
val_size: 0
logging_steps: 10
save_steps: 500
overwrite_output_dir: true
bf16: false
gradient_checkpointing: true
