# Qwen3-32B 模型 LoRA 微调配置文件 - 基于finetune.sh

# 基本配置
stage: sft
do_train: true
finetuning_type: lora
template: qwen3

# 继续微调设置

# 数据配置
# dataset: QM9S_all_train,MSD_all_train,mix_train,MSD_ir_train,MSD_cnr_train,MSD_hnr_train,MSD_hsqc_train,QM9S_ir_train,QM9S_uv_train,QM9S_raman_train,MSG_shuf_train
dataset: qm9s_all_train,MSD_all_train,mix_train,QM9S_ir_train,MB_train,MSG_train,MSD_nmr_train
cutoff_len: 1280
max_samples: 100000
preprocessing_num_workers: 64
dataloader_num_workers: 64

# 训练参数
learning_rate: 0.00005
num_train_epochs: 1.0
per_device_train_batch_size: 6
gradient_accumulation_steps: 4
lr_scheduler_type: cosine
max_grad_norm: 1.0
optim: adamw_torch
warmup_steps: 0

# LoRA 参数
lora_rank: 8
lora_dropout: 0.0
lora_target: all

# 输出配置
logging_steps: 100
save_steps: 5000
plot_loss: true

# 性能优化
enable_liger_kernel: true
bf16: true
packing: false
report_to: none
trust_remote_code: true
ddp_timeout: 180000000
include_num_input_tokens_seen: true
